language: objective-c
osx_image: xcode8

before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script:
    - xcodebuild test -target Persei.xcodeproj -scheme Persei -sdk iphonesimulator
