language: objective-c
before_install:
    - gem install cocoapods --no-rdoc --no-ri --no-document --quiet
script:
    - xcodebuild test -workspace Persei.xcodeproj -scheme Persei -sdk iphonesimulator
